services:
  db:
    image: postgres:16-alpine
    container_name: barokah-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: barokah
      POSTGRES_PASSWORD: barokah
      POSTGRES_DB: barokah
    ports:
      - '5433:5432'
    volumes:
      - barokah_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U barokah -d barokah']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  barokah_pgdata: