import {
  Accessibility,
  Apple,
  Armchair,
  Baby,
  Bath,
  BatteryCharging,
  BatteryFull,
  Bed,
  BriefcaseMedical,
  BusFront,
  Camera,
  Candy,
  Clock,
  Coffee,
  Compass,
  Cookie,
  DoorOpen,
  Ellipsis,
  Fan,
  Fuel,
  Gauge,
  Gift,
  Info,
  Lightbulb,
  Luggage,
  MapPinned,
  Megaphone,
  Monitor,
  Moon,
  Music,
  Navigation,
  Nfc,
  Pill,
  Plug,
  PlugZap,
  QrCode,
  Radio,
  Recycle,
  Route,
  Sandwich,
  Satellite,
  ShieldCheck,
  ShieldPlus,
  Smartphone,
  Snowflake,
  Sofa,
  Sparkles,
  Star,
  Sun,
  Thermometer,
  Ticket,
  TicketCheck,
  Toilet,
  Cable,
  Usb,
  Utensils,
  Video,
  Volume2,
  Wifi,
  Wind,
  Backpack,
  Zap,
  Tv,
  CupSoda,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import type { FacilityIcon } from '@/lib/facilities'

export const FACILITY_ICONS: Record<FacilityIcon, LucideIcon> = {
  armchair: Armchair,
  sofa: Sofa,
  bed: Bed,
  luggage: Luggage,
  backpack: Backpack,
  snowflake: Snowflake,
  fan: Fan,
  wind: Wind,
  thermometer: Thermometer,
  sun: Sun,
  moon: Moon,
  plug: Plug,
  'plug-zap': PlugZap,
  'usb-plug': Usb,
  cable: Cable,
  'battery-charging': BatteryCharging,
  'battery-full': BatteryFull,
  zap: Zap,
  lightbulb: Lightbulb,
  wifi: Wifi,
  tv: Tv,
  monitor: Monitor,
  'volume-2': Volume2,
  music: Music,
  radio: Radio,
  smartphone: Smartphone,
  video: Video,
  camera: Camera,
  'cup-soda': CupSoda,
  utensils: Utensils,
  sandwich: Sandwich,
  coffee: Coffee,
  cookie: Cookie,
  candy: Candy,
  apple: Apple,
  toilet: Toilet,
  bath: Bath,
  'door-open': DoorOpen,
  'shield-check': ShieldCheck,
  'shield-plus': ShieldPlus,
  'briefcase-medical': BriefcaseMedical,
  pill: Pill,
  baby: Baby,
  accessibility: Accessibility,
  ticket: Ticket,
  'ticket-check': TicketCheck,
  'qr-code': QrCode,
  nfc: Nfc,
  'map-pinned': MapPinned,
  navigation: Navigation,
  route: Route,
  compass: Compass,
  'bus-front': BusFront,
  fuel: Fuel,
  gauge: Gauge,
  satellite: Satellite,
  ellipsis: Ellipsis,
  star: Star,
  gift: Gift,
  megaphone: Megaphone,
  info: Info,
  clock: Clock,
  recycle: Recycle,
  sparkles: Sparkles,
}

export function FacilityIconBadge({ icon, className = '' }: { icon: FacilityIcon; className?: string }) {
  const Icon = FACILITY_ICONS[icon] ?? Armchair
  return <Icon size={14} className={className} />
}
